### ISSUE TITLE
Add to MELPA or Sly Contrib

### ISSUE THREAD

**Issue by noctuid** [PuercoPop/sly-repl-ansi-color#2]
It seems from capitaomorte/sly#38 that this will not be added to sly/contrib? If that's the case, would you be okay with putting this on MELPA? The file needs to be reformatted (with metadata added), but I'm willing to send a pull request for this if it's fine with you. I'm also willing to make the pull request to MELPA if you want.

**Comment by PuercoPop** [comment]
Sure go for it!

**Comment by noctuid** [comment]
I haven't made a pull request yet because it fails in the melpa sandbox due to sly failing to install correctly. I'm not sure why this happens, but I made an issue for it at  melpa/melpa#3573

**Comment by PuercoPop** [comment]
Landed on Melpa as of [PR 3595](https://github.com/melpa/melpa/pull/3595). I'd like to thank both @noctuid and @syohex for making the necessary changes. 

:tada: :clap:

**Comment by voobscout** [comment]
sly-repl-ansi-color is no longer on Melpa

**Comment by PuercoPop** [comment]
@voobscout sly-repl-ansi-color is now available in the [emacs-pe elpa](https://github.com/emacs-pe/emacs-pe.github.io/commit/c1323e60042bf98d9413229a465975fdb5fbdc3b).
`(emacs-pe '("emacs-pe" . "https://emacs-pe.github.io/packages/"))`
